
spring:
  application:
    name: openex-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/openex
    username: openex
    password: openex
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: "change-this-to-a-long-random-string-before-any-real-deployment-32chars-min"
  expiration-ms: 3600000

  market-sim:
  url: http://localhost:5001
  api-key: openex-secure-sim-key-2026